### ISSUE TITLE
How to use other programming languages

### ISSUE THREAD

**Issue by jonnieey** [kevin-bruton/mt_docker#1]
Followed instructions and the image built fine. 
How do i interface metatrader5 with python? 
Must I use darwinex server scripts (dwx_server_mt5)?

**Comment by kevin-bruton** [comment]
There is an EA included in the MT installation in the Docker image called FileConnection. It corresponds to the dwx_server_mt5. So on the MT side of things, everything is provided in the image. 

If you want to use python, you can use the client for python included here to see how to interface with it: https://github.com/darwinex/dwxconnect

**Comment by jonnieey** [comment]
Thanks, much appreciated.
